"""Pipeline step: score the ROI Scorecard with both methods and write the artifact.

The front end consumes this at build time. It carries a portfolio header per method
(Method 0 and Method 1) and one record per event that co-locates both methods'
estimates, so the Scorecard's method toggle and the Method 0 -> Method 1 delta are a
lookup, not a join. Every monetary figure is integer cents and every ratio is
derived from those cents, so the artifact is deterministic (spec §6). No truth, no
baseline generator — the same blind estimates ``method0`` and ``method1`` produce.

Determinism, as with the skeleton: no wall-clock, no unseeded value, canonical JSON
(sorted keys, fixed separators, LF newline). Events are emitted in canonical
promo_id order; ranking is the view's job.
"""

import json
from pathlib import Path

import cinderhaven_promo_response as pr
import pandas as pd

from incrementality import method0, method1

SCHEMA = "scorecard/v3"  # v3: split summary (imported) + full events (fetched), Option B

# <repo>/src/incrementality/build_scorecard.py -> <repo>
_REPO_ROOT = Path(__file__).resolve().parents[2]
# Gitignored and regenerated by the build — a committed copy could ship stale, the
# one outcome the build contract forbids (PLAN.md). A missing file fails the
# front-end build loudly rather than shipping yesterday's numbers.
#
# Option B (DECISIONS 2026-08-27): the ~5,900-event universe would put a ~3.75MB events
# array on the 30-second front door. So the imported artifact carries only the summary
# (portfolios, precomputed chart tiers, filter options, cross-estimable counts) plus a
# first page of the ranked list; the full events array is written to web/static/ and
# fetched on demand (once, cached) when a filter is touched or "show all" is clicked.
DEFAULT_OUT = _REPO_ROOT / "web" / "src" / "lib" / "data" / "scorecard.json"
EVENTS_OUT = _REPO_ROOT / "web" / "static" / "scorecard-events.json"

# First page of the ranked list: the top by net margin under each method (the list sorts
# net-margin descending), plus every story event, so the front door renders a real ranked
# list before the full fetch. The rest (mid-table and the biggest losers) load with it.
FIRST_PAGE_PER_METHOD = 150


def _str(value):
    return None if pd.isna(value) else str(value)


def _int(value):
    return None if pd.isna(value) else int(value)


def _float(value):
    return None if pd.isna(value) else float(value)


def _bool(value):
    return None if pd.isna(value) else bool(value)


# Method-independent identity, carried once per event. promo_id is the frame index,
# added explicitly in _event_records rather than read off the row.
_SHARED_FIELDS = {
    "sku": _str,
    "retailer_id": _str,
    "promo_type": _str,
    "plan_status": _str,
    "story_tag": _str,
    "accrued_cost_cents": _int,
}

# Per-method estimate. Every converter maps pandas NA/NaN to JSON null.
_METHOD_FIELDS = {
    "estimable": _bool,
    "exclusion_reason": _str,
    "n_stores_estimable": _int,
    "net_margin_cents": _int,
    "roi": _float,
    "lost_money": _bool,
    "subsidized_cost_share": _float,
    "baseline_exceeds_promoted": _bool,
}

# Method 1 only: the hierarchical-match relaxation regime dimension (spec §3.3).
_METHOD1_FIELDS = {**_METHOD_FIELDS, "match_relaxed_share": _float}


def _method_record(row, fields):
    # row[name] indexing (never getattr, which could return a Series attribute).
    return {name: convert(row[name]) for name, convert in fields.items()}


def _event_records(events0, events1):
    """One record per event co-locating both methods, in canonical promo_id order."""
    e0 = events0.set_index("promo_id")
    e1 = events1.set_index("promo_id")
    records = []
    for promo_id in sorted(e0.index):
        row0 = e0.loc[promo_id]
        row1 = e1.loc[promo_id]
        record = {name: convert(row0[name]) for name, convert in _SHARED_FIELDS.items()}
        record["promo_id"] = promo_id  # index, not a column on the row
        record["method0"] = _method_record(row0, _METHOD_FIELDS)
        record["method1"] = _method_record(row1, _METHOD1_FIELDS)
        records.append(record)
    return records


def _tiers(records, method):
    """Chart tier COUNTS for a method, order [lost, 1-2x, 2-4x, 4x+].

    Replicates the front-end's tiersFor exactly, precomputed so the 30-second chart
    renders without the full events array (Option B).
    """
    est = [r for r in records if r[method]["estimable"]]
    made = [r for r in est if not r[method]["lost_money"]]

    def roi_in(rec, lo, hi):
        v = rec[method]["roi"]
        return v is not None and lo <= v < hi

    return [
        sum(1 for r in est if r[method]["lost_money"]),
        sum(1 for r in made if roi_in(r, 1, 2)),
        sum(1 for r in made if roi_in(r, 2, 4)),
        sum(1 for r in made if r[method]["roi"] is None or r[method]["roi"] >= 4),
    ]


def _filter_options(records):
    """Distinct sorted values per filter dimension — replicates filters.js optionsFor."""

    def line(rec):
        return rec["sku"].split("-")[1]

    return {
        "retailer": sorted({r["retailer_id"] for r in records}),
        "line": sorted({line(r) for r in records}),
        "type": sorted({r["promo_type"] for r in records}),
        "status": sorted({r["plan_status"] for r in records}),
    }


def _cross_estimable(records):
    """Per method: how many of its non-estimable events the other method can score."""

    def count(method, other):
        return sum(1 for r in records if not r[method]["estimable"] and r[other]["estimable"])

    return {
        "method0": count("method0", "method1"),
        "method1": count("method1", "method0"),
    }


def _summary(records):
    return {
        "tiers": {"method0": _tiers(records, "method0"), "method1": _tiers(records, "method1")},
        "filter_options": _filter_options(records),
        "cross_estimable": _cross_estimable(records),
        # How many rows the first page shows per method before the full fetch, so the
        # view can cap the union first_page to the true top-N under the active method.
        "first_page_size": FIRST_PAGE_PER_METHOD,
    }


def _first_page(records):
    """The ranked-list first page: top net-margin events per method + every story event."""
    ids = {r["promo_id"] for r in records if r["story_tag"] is not None}
    for method in ("method0", "method1"):
        estimable = [
            r
            for r in records
            if r[method]["estimable"] and r[method]["net_margin_cents"] is not None
        ]
        top = sorted(estimable, key=lambda r: r[method]["net_margin_cents"], reverse=True)
        ids.update(r["promo_id"] for r in top[:FIRST_PAGE_PER_METHOD])
    # Canonical order; the view re-sorts by the active method.
    return [r for r in records if r["promo_id"] in ids]


def compute():
    """The both-method Scorecard artifact as a plain dict of JSON-ready primitives."""
    result0 = method0.estimate()
    result1 = method1.estimate()
    return {
        "schema": SCHEMA,
        # Provenance: an ROI figure is unmoored without its data generation
        # (DECISIONS.md). Deterministic given the pinned SHA.
        "package_version": pr.__version__,
        "portfolios": {
            "method0": result0.portfolio,
            "method1": result1.portfolio,
        },
        "events": _event_records(result0.events, result1.events),
    }


def serialize(payload):
    """Canonical JSON bytes-as-str: sorted keys, fixed separators, trailing LF."""
    return json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n"


def build(out_path=DEFAULT_OUT, events_out=EVENTS_OUT):
    """Write the split Scorecard artifacts (summary + full events). Returns the summary path.

    write_bytes, not write_text: text mode translates LF -> CRLF on Windows, which would
    make the artifact differ byte-for-byte between a Windows dev machine and Linux CI.
    Determinism is byte-identical.
    """
    full = compute()
    records = full["events"]
    summary_payload = {
        "schema": SCHEMA,
        "package_version": full["package_version"],
        "portfolios": full["portfolios"],
        "summary": _summary(records),
        "first_page": _first_page(records),
    }
    events_payload = {
        "schema": SCHEMA,
        "package_version": full["package_version"],
        "events": records,
    }
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(serialize(summary_payload).encode("utf-8"))
    events_out = Path(events_out)
    events_out.parent.mkdir(parents=True, exist_ok=True)
    events_out.write_bytes(serialize(events_payload).encode("utf-8"))
    return out_path


def main():
    path = build()
    print(f"wrote {path} + {EVENTS_OUT.name}")


if __name__ == "__main__":
    main()
