"""Pipeline step: score the ROI Scorecard with both methods and write the artifact.

The front end consumes this at build time. It carries a portfolio header per method
(Method 0 and Method 1) and one record per event that co-locates both methods'
estimates, so the Scorecard's method toggle and the Method 0 -> Method 1 delta are a
lookup, not a join. Every monetary figure is integer cents and every ratio is
derived from those cents, so the artifact is deterministic (spec §6). No truth, no
baseline generator — the same blind estimates ``method0`` and ``method1`` produce.

Determinism, as with the skeleton: no wall-clock, no unseeded value, canonical JSON
(sorted keys, fixed separators, LF newline). Events are emitted in canonical
promo_id order; ranking is the view's job.
"""

import json
from pathlib import Path

import cinderhaven_promo_response as pr
import pandas as pd

from incrementality import method0, method1

SCHEMA = "scorecard/v2"

# <repo>/src/incrementality/build_scorecard.py -> <repo>
_REPO_ROOT = Path(__file__).resolve().parents[2]
# Gitignored and regenerated by the build — a committed copy could ship stale, the
# one outcome the build contract forbids (PLAN.md). A missing file fails the
# front-end build loudly rather than shipping yesterday's numbers.
DEFAULT_OUT = _REPO_ROOT / "web" / "src" / "lib" / "data" / "scorecard.json"


def _str(value):
    return None if pd.isna(value) else str(value)


def _int(value):
    return None if pd.isna(value) else int(value)


def _float(value):
    return None if pd.isna(value) else float(value)


def _bool(value):
    return None if pd.isna(value) else bool(value)


# Method-independent identity, carried once per event. promo_id is the frame index,
# added explicitly in _event_records rather than read off the row.
_SHARED_FIELDS = {
    "sku": _str,
    "retailer_id": _str,
    "promo_type": _str,
    "plan_status": _str,
    "story_tag": _str,
    "accrued_cost_cents": _int,
}

# Per-method estimate. Every converter maps pandas NA/NaN to JSON null.
_METHOD_FIELDS = {
    "estimable": _bool,
    "exclusion_reason": _str,
    "n_stores_estimable": _int,
    "net_margin_cents": _int,
    "roi": _float,
    "lost_money": _bool,
    "subsidized_cost_share": _float,
    "baseline_exceeds_promoted": _bool,
}

# Method 1 only: the hierarchical-match relaxation regime dimension (spec §3.3).
_METHOD1_FIELDS = {**_METHOD_FIELDS, "match_relaxed_share": _float}


def _method_record(row, fields):
    # row[name] indexing (never getattr, which could return a Series attribute).
    return {name: convert(row[name]) for name, convert in fields.items()}


def _event_records(events0, events1):
    """One record per event co-locating both methods, in canonical promo_id order."""
    e0 = events0.set_index("promo_id")
    e1 = events1.set_index("promo_id")
    records = []
    for promo_id in sorted(e0.index):
        row0 = e0.loc[promo_id]
        row1 = e1.loc[promo_id]
        record = {name: convert(row0[name]) for name, convert in _SHARED_FIELDS.items()}
        record["promo_id"] = promo_id  # index, not a column on the row
        record["method0"] = _method_record(row0, _METHOD_FIELDS)
        record["method1"] = _method_record(row1, _METHOD1_FIELDS)
        records.append(record)
    return records


def compute():
    """The both-method Scorecard artifact as a plain dict of JSON-ready primitives."""
    result0 = method0.estimate()
    result1 = method1.estimate()
    return {
        "schema": SCHEMA,
        # Provenance: an ROI figure is unmoored without its data generation
        # (DECISIONS.md). Deterministic given the pinned SHA.
        "package_version": pr.__version__,
        "portfolios": {
            "method0": result0.portfolio,
            "method1": result1.portfolio,
        },
        "events": _event_records(result0.events, result1.events),
    }


def serialize(payload):
    """Canonical JSON bytes-as-str: sorted keys, fixed separators, trailing LF."""
    return json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n"


def build(out_path=DEFAULT_OUT):
    """Compute and write the artifact. Returns the path written."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # write_bytes, not write_text: text mode translates LF -> CRLF on Windows, which
    # would make the artifact differ byte-for-byte between a Windows dev machine and
    # Linux CI. Determinism is byte-identical.
    out_path.write_bytes(serialize(compute()).encode("utf-8"))
    return out_path


def main():
    path = build()
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
