"""Pipeline step: run Method 0 and write the ROI Scorecard artifact.

The front end consumes this at build time. It carries the portfolio header (the
CFO numbers, spec section 2.6) and one record per event; every monetary figure is
integer cents and every ratio is derived from those cents, so the artifact is
deterministic (spec section 5). No truth, no baseline generator — this is the
same blind estimate ``method0`` produces, serialized.

Determinism, as with the skeleton: no wall-clock, no unseeded value, canonical
JSON (sorted keys, fixed separators, LF newline). Same pinned package + same code
→ byte-identical bytes, which is what the reproducibility test checks.

Ranking is a view concern and the Scorecard view does not exist yet, so events are
emitted in a stable canonical order (by promo_id). The front end ranks; the
pipeline stays order-deterministic.
"""

import json
from pathlib import Path

import cinderhaven_promo_response as pr
import pandas as pd

from incrementality import method0

SCHEMA = "scorecard/v1"

# <repo>/src/incrementality/build_scorecard.py -> <repo>
_REPO_ROOT = Path(__file__).resolve().parents[2]
# Gitignored and regenerated by the build — a committed copy could ship stale,
# the one outcome the build contract forbids (PLAN.md). A missing file fails the
# front-end build loudly rather than shipping yesterday's numbers.
DEFAULT_OUT = _REPO_ROOT / "web" / "src" / "lib" / "data" / "scorecard.json"


def _str(value):
    return None if pd.isna(value) else str(value)


def _int(value):
    return None if pd.isna(value) else int(value)


def _float(value):
    return None if pd.isna(value) else float(value)


def _bool(value):
    return None if pd.isna(value) else bool(value)


# Column -> converter for the per-event records. Every converter maps pandas
# missing values (NA / NaN) to JSON null; there is no NaN in valid JSON.
_EVENT_FIELDS = {
    "promo_id": _str,
    "sku": _str,
    "retailer_id": _str,
    "promo_type": _str,
    "plan_status": _str,
    "story_tag": _str,
    "estimable": _bool,
    "n_stores_estimable": _int,
    "net_margin_cents": _int,
    "accrued_cost_cents": _int,
    "roi": _float,
    "lost_money": _bool,
    "subsidized_cost_share": _float,
    "baseline_exceeds_promoted": _bool,
}


def _event_records(events_df):
    """The event rows as JSON-ready dicts, in canonical (promo_id) order."""
    ordered = events_df.sort_values("promo_id", kind="stable")
    records = []
    for row in ordered.itertuples(index=False):
        record = {name: convert(getattr(row, name)) for name, convert in _EVENT_FIELDS.items()}
        records.append(record)
    return records


def compute():
    """The Scorecard artifact as a plain dict of JSON-ready primitives."""
    result = method0.estimate()
    return {
        "schema": SCHEMA,
        # Provenance: an ROI figure is unmoored without its data generation
        # (DECISIONS.md). Deterministic given the pinned SHA.
        "package_version": pr.__version__,
        "portfolio": result.portfolio,
        "events": _event_records(result.events),
    }


def serialize(payload):
    """Canonical JSON bytes-as-str: sorted keys, fixed separators, trailing LF."""
    return json.dumps(payload, sort_keys=True, separators=(",", ":")) + "\n"


def build(out_path=DEFAULT_OUT):
    """Compute and write the artifact. Returns the path written."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    # write_bytes, not write_text: text mode translates LF -> CRLF on Windows,
    # which would make the artifact differ byte-for-byte between a Windows dev
    # machine and Linux CI. Determinism is byte-identical.
    out_path.write_bytes(serialize(compute()).encode("utf-8"))
    return out_path


def main():
    path = build()
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
