<script>
	// Imported at build time. The Python pipeline writes this file; if it is
	// missing, this import fails the build loudly rather than shipping a stale
	// artifact (the build contract, PLAN.md). It is NOT committed — it is
	// regenerated by `python -m incrementality.build_skeleton`.
	import skeleton from '$lib/data/skeleton.json';

	const fmt = new Intl.NumberFormat('en-US');
</script>

<main>
	<p class="tag">Walking skeleton — pipeline proof, not a deliverable</p>

	<h1>{fmt.format(skeleton.total_observed_units)}</h1>
	<p class="sub">total observed units across the promo-event scan series</p>

	<dl>
		<div>
			<dt>Promo events</dt>
			<dd>{fmt.format(skeleton.event_count)}</dd>
		</div>
		<div>
			<dt>Scan rows</dt>
			<dd>{fmt.format(skeleton.scan_row_count)}</dd>
		</div>
		<div>
			<dt>Data package</dt>
			<dd>cinderhaven-promo-response v{skeleton.package_version}</dd>
		</div>
	</dl>

	<p class="note">
		Every number here is <strong>observed only</strong> — computed in Python
		from <code>pr.load()</code>, written as JSON, rendered by this static
		build. No estimator, no baseline, no truth. The ROI Scorecard, Method&nbsp;0,
		and the accuracy view come later; this page exists to prove the pipe.
	</p>
</main>

<style>
	main {
		max-width: 40rem;
		margin: 0 auto;
		padding: 3rem 1.25rem;
		font-family: system-ui, sans-serif;
		color: #1a1a1a;
	}
	.tag {
		font-size: 0.75rem;
		letter-spacing: 0.04em;
		text-transform: uppercase;
		color: #6b6b6b;
		margin: 0 0 1.5rem;
	}
	h1 {
		font-size: clamp(2.5rem, 8vw, 4rem);
		font-variant-numeric: tabular-nums;
		margin: 0;
		line-height: 1;
	}
	.sub {
		margin: 0.5rem 0 2.5rem;
		color: #4a4a4a;
	}
	dl {
		display: grid;
		gap: 1rem;
		margin: 0 0 2.5rem;
	}
	dl div {
		display: flex;
		justify-content: space-between;
		border-bottom: 1px solid #e5e5e5;
		padding-bottom: 0.5rem;
	}
	dt {
		color: #4a4a4a;
	}
	dd {
		margin: 0;
		font-variant-numeric: tabular-nums;
	}
	.note {
		font-size: 0.9rem;
		line-height: 1.5;
		color: #4a4a4a;
	}
	code {
		font-size: 0.85em;
		background: #f2f2f2;
		padding: 0.1em 0.3em;
		border-radius: 3px;
	}
</style>
